const commonAbout = 'Interested to become';

export const servicesData = [
  {
    category: 'Banking Services',
    services: [
      {
        id: 1,
        name: 'AePS',
        icon: '../../public/aeps-1.png',
        color: 'bg-green-400',
        about: commonAbout,
      },
      {
        id: 2,
        name: 'Aadhar Pay',
        icon: '../../public/aadhar-pay.png',
        color: 'bg-purple-400',
        about: commonAbout,
      },
      {
        id: 3,
        name: 'Cash Deposit',
        icon: '../../public/Cash-Deposit (1).png',
        color: 'bg-teal-500',
        about: commonAbout,
      },
      {
        id: 4,
        name: 'Account Opening',
        icon: '../../public/bank (1).png',
        color: 'bg-orange-500',
        about: commonAbout,
      },
      {
        id: 5,
        name: 'Money Transfer',
        icon: '../../public/money-transfer.png',
        color: 'bg-purple-400',
        about: commonAbout,
      },
      {
        id: 6,
        name: 'Loan Apply',
        icon: '../../public/loan.png',
        color: 'bg-teal-500',
        about: commonAbout,
      },
      {
        id: 7,
        name: 'Credit Card Apply',
        icon: '../../public/card.png',
        color: 'bg-orange-500',
        about: commonAbout,
      },
      {
        id: 8,
        name: 'Loan Repayment',
        icon: '../../public/loan (1).png',
        color: 'bg-purple-400',
        about: commonAbout,
      },
      {
        id: 9,
        name: 'CSP Kiosk Banking',
        icon: '../../public/bank (1).png',
        color: 'bg-teal-500',
        about: commonAbout,
      },
      {
        id: 10,
        name: 'Micro ATM',
        icon: '../../public/mini-atm.png',
        color: 'bg-orange-500',
        about: commonAbout,
      },
    ],
  },
  {
    category: 'Recharge & Bill Payments',
    services: [
      {
        id: 11,
        name: 'Mobile Recharge',
        icon: '../../public/mobile-recharge.png',
        color: 'bg-orange-500',
      },
      {
        id: 12,
        name: 'DTH Recharge',
        icon: '../../public/DTH.png',
        color: 'bg-teal-500',
      },
      {
        id: 13,
        name: 'Electricity Bill',
        icon: '../../public/electrcity-bill.png',
        color: 'bg-green-400',
      },
      {
        id: 14,
        name: 'Water Bill',
        icon: '../../public/Water.png',
        color: 'bg-orange-500',
      },
      {
        id: 15,
        name: 'Gas Bill',
        icon: '../../public/gas.png',
        color: 'bg-purple-400',
      },
      {
        id: 16,
        name: 'Insurance',
        icon: '../../public/insurance.png',
        color: 'bg-purple-400',
      },
      {
        id: 17,
        name: 'Landline Bill',
        icon: '../../public/landline.png',
        color: 'bg-orange-500',
      },
      {
        id: 18,
        name: 'Credit Card Bill',
        icon: '../../public/card.png',
        color: 'bg-teal-500',
      },
      {
        id: 19,
        name: 'LIC Bill',
        icon: '../../public/lic-1.png',
        color: 'bg-green-400',
      },
      {
        id: 20,
        name: 'FASTag',
        icon: '../../public/fastag.png',
        color: 'bg-orange-500',
      },
    ],
  },

  {
    category: 'Government Services',
    services: [
      {
        id: 37,
        name: 'Aadhar Udyog',
        icon: '../../public/aadhar (1).png',
        color: 'bg-green-400',
      },
      {
        id: 38,
        name: 'Aadhar Update',
        icon: '../../public/aadhar (2).png',
        color: 'bg-blue-400',
      },
      {
        id: 39,
        name: 'PAN NSDL',
        icon: '../../public/Pan-card (1).png',
        color: 'bg-red-500',
      },
      {
        id: 40,
        name: 'PAN UTI',
        icon: '../../public/pan-card.png',
        color: 'bg-yellow-500',
      },
      {
        id: 41,
        name: 'Driving Licence',
        icon: '../../public/Driving-Licence.png',
        color: 'bg-teal-500',
      },
      {
        id: 42,
        name: 'Voter ID',
        icon: '../../public/voter-id.png',
        color: 'bg-purple-400',
      },
      {
        id: 43,
        name: 'Death Certificate',
        icon: '../../public/Death-Certificate-1.png',
        color: 'bg-orange-400',
      },
      {
        id: 44,
        name: 'Disability Certificate',
        icon: '../../public/Disability-Certificate.png',
        color: 'bg-red-400',
      },
      {
        id: 45,
        name: 'Income Certificate',
        icon: '../../public/income-certificate.png',
        color: 'bg-blue-500',
      },
      {
        id: 46,
        name: 'Domicile Certificate',
        icon: '../../public/domicile-certificate.png',
        color: 'bg-green-500',
      },
      {
        id: 47,
        name: 'E Shram Card',
        icon: '../../public/e-shram.png',
        color: 'bg-teal-500',
      },
      {
        id: 48,
        name: 'Aadhar Center Apply',
        icon: '../../public/aadhar (1).png',
        color: 'bg-yellow-400',
      },
      {
        id: 49,
        name: 'Passport Apply',
        icon: '../../public/passport.png',
        color: 'bg-orange-500',
      },
      {
        id: 50,
        name: 'PMJAY',
        icon: '../../public/labour-card.png',
        color: 'bg-purple-500',
      },
      {
        id: 51,
        name: 'Labour Card',
        icon: '../../public/labour-card.png',
        color: 'bg-blue-500',
      },
      {
        id: 52,
        name: 'Ration Card',
        icon: '../../public/ration-card.png',
        color: 'bg-red-500',
      },
    ],
  },
  {
    category: 'Registration & Tax Filing Services',
    services: [
      {
        id: 21,
        name: 'GST Registration',
        icon: '../../public/gst-Registration.png',
        color: 'bg-blue-500',
      },
      {
        id: 22,
        name: 'One Person Company',
        icon: '../../public/one-person-company.png',
        color: 'bg-red-500',
      },
      {
        id: 23,
        name: 'Private Limited Registration',
        icon: '../../public/private-Limited.png',
        color: 'bg-green-500',
      },
      {
        id: 24,
        name: 'Change Business Name',
        icon: '../../public/change-business-name-1.png',
        color: 'bg-yellow-500',
      },
      {
        id: 25,
        name: 'Add/Remove Partner',
        icon: '../../public/Add-remove-partner.png',
        color: 'bg-teal-500',
      },
      {
        id: 26,
        name: 'GST Correction',
        icon: '../../public/gst-Registration.png',
        color: 'bg-orange-500',
      },
      {
        id: 27,
        name: 'Section 8 Company',
        icon: '../../public/Section-8-company.png',
        color: 'bg-purple-500',
      },
      {
        id: 28,
        name: 'Income Tax Return',
        icon: '../../public/income-tax-return.png',
        color: 'bg-green-400',
      },
      {
        id: 29,
        name: 'TDS Return',
        icon: '../../public/tds-return.png',
        color: 'bg-blue-400',
      },
      {
        id: 30,
        name: 'TAN Registration',
        icon: '../../public/tan-registration.png',
        color: 'bg-red-400',
      },
      {
        id: 31,
        name: 'GST Return',
        icon: '../../public/gst-Registration.png',
        color: 'bg-yellow-400',
      },
      {
        id: 32,
        name: 'FSSAI',
        icon: '../../public/fssai-registration.png',
        color: 'bg-teal-400',
      },
    ],
  },
  {
    category: 'Travel Services',
    services: [
      {
        id: 33,
        name: 'Bus Booking',
        icon: '../../public/bus-booking.png',
        color: 'bg-orange-500',
      },
      {
        id: 34,
        name: 'Hotel Booking',
        icon: '../../public/hotel-booking.png',
        color: 'bg-blue-500',
      },
      {
        id: 35,
        name: 'Flight Booking',
        icon: '../../public/flight-1.png',
        color: 'bg-teal-500',
      },
      {
        id: 36,
        name: 'Train Booking',
        icon: '../../public/IRCTC.png',
        color: 'bg-purple-500',
      },
    ],
  },
];
